config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/payment', to: 'payments#payment'
  get 'carts/cart'
  root 'home#index'
  get 'main', to: 'home#main', as: :main
  resources :users
  # resources :home , only: [:index , :main]
  get '/login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'users/new', to: 'users#new'
  get 'about_us', to: 'home#about_us'
  get 'home', to: 'home#index'
  get 'users/home', to: 'home#index'
  get 'users/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  # match 'items/index',:to=>'items#index',:via=>:get
  get '/show/snacks', to: 'items#snacks'
  get '/show/papads&Fryums', to: 'items#papads_fryums'
  get '/show/healthmix', to: 'items#healthmix'
  get '/show/sweets', to: 'items#sweets'
  get '/show/jaggerysweets', to: 'items#jaggerysweets'
  get '/show/pickles', to: 'items#pickles'
  get '/item/:item_id', to: 'items#show_selected_item', as: :item_id

  # resources :add
  get '/show/add', to: 'items#add'
  post '/items', to: 'items#create'
  get '/wishlist/:wishlist_product_id', to: 'home#wishlist_items'
  get '/wish-list', to: 'home#wishlist'
  get '/show/wish-list', to: 'home#wishlist'
  get '/cart', to: 'carts#cart'
  # get '/cart', to: 'carts#show_cart_items'
  get 'item/item/cart_page/:product_id', to: 'carts#create'
  get 'cart_page/:cart_item_id', to: 'carts#delete_item'
  delete '/show/wish-list/:wishlist_product_id', to: 'home#delete_wishlist_item'
  delete '/wish-list/:wishlist_product_id', to: 'home#delete_wishlist_item'
  get '/cart/:product_id', to: 'carts#create'

  get '/item/cart_page/:prod_id', to: 'items#add_to_cart'
  get '/wl/:item_id', to: 'home#add_wl_item_to_cart'

  get 'search',to: "home#search"
  get '/add_card', to: "payments#add_card"

  post '/card_detail', to: "payments#create_card"
  get '/payment', to: "payments#payment"
  get 'address', to: "payments#address"
  get 'items/item/cart_page/:prodt_id', to: "items#cart_single_item"  , as: :items_id
  get 'items/:prodt_id', to: "items#cart_single_item" 
  get 'user_profile', to: 'home#user_profile' 
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in
 
  def index 
  end

  def main 
   end
 
   def user_profile
     
   end
def search
  @filtered_items = Item.where('category LIKE ? OR item_name LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%")
  p "==============================================="
  p "==============================================="
  p "==============================================="
  p @filtered_items
end

  def wishlist
    @items = Item.joins(:wishlist).all.map do |wishlist|
      wishlist
    end
    # puts " @items is #{@items}"
    # current_user = session[:current_user_id]
    # @item= Wishlist.where(user_id: current_user['id']).map do |saved|
    #   saved
    # end
    # "@item is #{@item}"
  end

  def wishlist_items
    current_user = session[:current_user_id]
    product_id = params[:wishlist_product_id]
    # puts " current_user is #{current_user}"
    if current_user.nil?
      flash[:alert] = 'Please Login!'
      puts "cur_user_id is #{current_user}"
      # redirect_to '/show/snacks'
      redirect_back(fallback_location: root_path)
    else
     
      cur_user_id = session[:current_user_id]
      find_prod_id = Wishlist.find_by(item_id: product_id)
      puts "Hhhhhhhhhhhhhhhhhhhhhhhhhhh"
      puts "product_id is #{product_id}"
      puts "find_prod_id is #{find_prod_id}"
      # puts find_prod_id.inspect
        if find_prod_id
          flash[:alert] = 'Already product exists!'
           redirect_back(fallback_location: root_path)
        else
          
          @wishlist_products = Wishlist.create item_id: product_id, user_id: cur_user_id['id'] 
          flash[:alert] = 'Added to Wishlist!'
          puts "+++++++++++++++"
          puts "+++++++++++++++"
          puts "+++++++++++++++"
          puts "product_id is #{product_id}"
          # puts "find_prod_id is #{find_prod_id['item_id']}"
          # puts product_id != find_prod_id['item_id']
          # flash[:alert] = 'Added to wishlist!'
         
          redirect_back(fallback_location: root_path) 
         
        end
        end
        end

  def delete_wishlist_item
    cur_user_id = session[:current_user_id]
    del_id = params[:wishlist_product_id]
    puts "wishlist_product_id is #{del_id}"
    del_wishlist = Wishlist.find_by(item_id: del_id)
    del_wishlist.destroy
    del_wishlist.save
    # redirect_to '/show/wish-list'
    redirect_back(fallback_location: root_path)
  end

  def add_wl_item_to_cart
    current_user = session[:current_user_id]
    puts " current_user is #{current_user}"
    if current_user.nil?
      flash[:alert] = 'Please Login!'
      puts "cur_user_id is #{current_user}"
      # redirect_to '/show/wish-list'
      redirect_back(fallback_location: root_path)
    else

      item_id = params[:item_id]

      remove_wl_item = Wishlist.find_by(item_id: item_id)
      remove_wl_item.destroy
      @wl_item_to_cart = Cart.create item_id: item_id, user_id: current_user['id']
      # redirect_to '/show/wish-list'
      flash[:alert] = 'Successfully added to cart!'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/about_us.html.erb
<div class="nav_bar">
<div class="ul_div">
    <ul>
        <a href="home"><li>Home</li></a>
        <a href="#"><li>About_us</li></a>
        <a href="login"><li>Log In</li></a>
    </ul>
</div>
</div>
  <div class="para">
      <p class='Question'>What is Mom's Delish ? </p><br>
      <%= image_tag 'happy.jpg' , alt: 'Happiness' , class: 'fam_pic'%>
      <div class='para_div'>
      
      <p class='paragraph'>
      <b>Happiness is Homemade❤️!</b> What is so special about homemade ? The answer is quite simple and straight. Anything homemade is not just tasty and healthy, but has a very special ingredient called unconditional love in it. One thing we would all cherish our entire lifetime would be our visits to our Grandmother's home. She would surprise us everytime with her culinary skills preparing a range of traditional delights and sometimes she even tries her hand into baking to makes some amazing cakes and cookies for her grandchildren. From time she gets to know our visit, she would start stocking up her big steel boxes with heavenly sweets, snacks and a range of other homemade delights that would beat any brand in the world hands down.
          The mission of Moms Delish is just to bring back those priceless golden childhood memories by unearthing the traditional Indian delights of our Grandmothers through our network of expert home chefs and small home brands.The range of delights that gets into the shelves of our store like Athirasam, Murukku, Filter coffee powder, Ghee, Rice pappads, Avakkai, Idly podi, Puliyogare paste etc is nothing but a tribute to the selfless relationship called 'The Grandmother'.

          In addition to the traditional Indian delicacies, we also do have a range of homemade chocolates, cookies, brownies, cream buns, peanut butter, chocolate spreads, fruit jams, squashes and much more surprises for the recent generation but with a healthy and homemade twist.

          Our recent additions - Vegan and gluten free sweets & snacks, Instant breakfast mixes, healthy porridge mixes and finally the farm fresh organic grocers sourced directly from the small farmers has made Sweet Karam Coffee, India's favourite destination good food store for your entire family with zero preservatives and zero toxic chemicals.

          So, experience our tradition but with a healthy and homemade twist @ www.Moms_delish.in and unleash instant happiness because..
          'Happiness is Homemade'❤️...</p>
      </div>
  </div>
    
  <!-- <div class="para">
    <p>What is Mom's Delish ? </p>
</div> -->

app/views/home/index.html.erb
<div id="whole_div">

    <link rel="icon" type="image/x-icon" href="./assets/images/snacks1.jpeg">
    <link href='https://fonts.googleapis.com/css?family=Aclonica' rel='stylesheet'>
<%# <img src="./app/assets/images/snacks1.jpeg" alt="bg"> %>
 <%= image_tag 'momsdelishlogo.png', alt: 'bg', class: 'logo'  %> 
<ul class="nav">
    <li><a href="#" class="home">Home</a></li>
    <li><a href="about_us" class="about">About us</a></li>
    <li><a href="login" id="log" class="about" >Login</a></li>
    <%# <li><a href="Index.html"><%= image_tag 'user_icon.png', alt: 'user', class:'user'</a></li>  %>
</ul>

<p class="content">
    Get Exclusive <br>Regional Snacks<br> of India At your<br> Doorstep
</p>
<p class="tagline">
    Experience the taste of mommy's snacks
</p>
 <%= image_tag 'moms_logo.png', alt: 'moms_delish', class:'moms_logo' %>
 <!-- <input type="button" value="Get Started" class="btn"> -->
 <button class="btn"><a href="main">Get Started</a></button>
 
<div class="cont_img">
    <%= image_tag 'Ready-to-cook.png', alt: 'Ready-to-cook.png' %>
    <p>Ready to eat</p>
    <%= image_tag 'Daily-Wholesome-Nutrition.png' , alt: 'Daily-Wholesome-Nutrition.png' %>
    <p>Daily wholesome <br>Nutrition</p>
    <%= image_tag 'Delicious-Home-Made-Taste.png' , alt: 'Delicious-Home-Made-Taste.png' %>
    <p>Home made <br>Delicious taste</p>
    <%= image_tag 'Promise-of-Quality.png' , alt: 'Promise-of-Quality.png' %>
    <p>Promise of quality</p>
    <%= image_tag 'Hands-free-Hygenic-Preparation.png' , alt: 'Hands-free-Hygenic-Preparation.png' %>
    <p>Hands-Free <br> Preparation</p>
</div>
<div class="testi">
    <p class="testimonial">Testimonial</p>
    <%= image_tag 'chat_bubble.png' , alt: 'speech-bubble', class: 'review' %>
    <%= image_tag 'ladoos.png' , alt: 'speech-bubble', class: 'item1' %>
    <%# <%= image_tag 'w_cus.png' , alt: 'speech-bubble', class: 'customer' %> 
    <p class="s_text">Hi I'm Sangeetha. Recently I purchased home made ladoos <br>from mom's delish. It was amazing and I have got health mix<br> that also tastes very good. It contains lot of minerals and protein. </p>
    <%= image_tag 'Chat.png' , alt: 'speech-bubble', class: 'review' %>
    <%= image_tag 'raagi_malt.png' , alt: 'speech-bubble', class: 'item2' %>
    <%# <p>Hands-Free <br> Preparation</p> %>
    <%# <%= image_tag 'm_cus.png' , alt: 'speech-bubble', class: 'customer' %>
    <p class="h_text">Hi I'm Nithish.Few weeks ago, I have purchased home made <br> idly powderfrom mom's delish. It was amazing and I have got <br>health mix like raagi malt that also tastes very good. It contains <br>lot of minerals and protein. </p>
    <%= image_tag 'w_cus.png' , alt: 'speech-bubble', class: 'cus1'%>
    <%= image_tag 'm_cus.png' , alt: 'speech-bubble', class: 'cus2' %> 
</div>

<footer> 
<div class="f1">
    <p>Get In Touch</p>
    <p class="underscore1">_______</p>
    <%= image_tag 'mail.png' , alt: 'speech-bubble', class: ''%>
    <a href=""><p class="side_con">Moms_Delish@gmail.com</p></a>
    <%= image_tag 'phone.png' , alt: 'speech-bubble', class: '' %> 
     <a href=""><p class="side_con">7395993654 / 7695993654 </p></a>
</div>

<div class="f2">
    <p>Moms Delish</p>
    <p class="underscore1">_______</p>
    <a href=""><p class="f2_p">Customer Review</p></a>
    <a href=""><p class="f2_p">Our blogs</p></a>
    <a href=""><p class="f2_p">Terms & Conditions</p></a>
</div>

<div class="f3">
    <p>Download the app</p>
    <p class="underscore1">_______</p>
    <a href=""><%= image_tag 'playstore.png' , alt: 'speech-bubble', class: 'app_download'%></a>
    
    <a href=""> <%= image_tag 'app-store.png' , alt: 'speech-bubble', class: 'app_download' %> </a>
</div>
<div class="">
    <p></p>
</div>

<%# <%= <img src="./assets/images/" alt=""  %>
</footer>
</div>


<!-- <script>
    function show_login(){
        document.getElementById("whole_div").style.display="none";
        document.getElementById("login").style.display="";
    }

    // function cancel(){
    //     document.getElementById("whole_div").style.display="";
    //     document.getElementById("login").style.display="none";
    // }
</script> -->

app/views/home/main.html.erb
<div class="nav_con">
  <div class="nav_subCon">
  <form action='/search'>
    <input type="text" name='q' placeholder="Find your snack" class="search">
    <%= image_tag 'Search.png', alt: 'Search_Icon', class: 'search_img'%>
  </form>
    <div class="heart">
      <div class="drop-down-container">
        <a class="ace"  href=''> <%= image_tag 'User.png', alt: 'Search_Icon', class: 'icons', id: 'user' %>
       
         <% if session[:current_user_id]  == nil %> 
          <div id="log" class="drop-down">
            <ul>
              <li><a href="/login">Login</a></li>
                <%# <% else %> 
                <%# <li><a href="/logout" data-method="delete">Log Out</a></li> %>
               
            </ul>
          </div>
        </a>
      </div>
      <%else%>
       <div id="log" class="drop-down">
            <ul>
              <%# <li><a href="/login">Login</a></li> %>
               
                <li><a href="/logout" data-method="delete">Log Out</a></li>
               
            </ul>
          </div>
        </a>
      </div>
        <%end %>  

      
    <a href='wish-list'> <%= image_tag 'favorite.png', alt: 'Search_Icon', class: 'icons'%></a>
    <a href='/cart'> <%= image_tag 'cart.png', alt: 'Search_Icon', class: 'icons'%></a>
  </div>
  </div>
  
  <div class="nav_div">
    <ul>
      <li><a href="/show/pickles">Pickles</a></li>
        
      <li><a href="/show/papads&Fryums">Papads & Fryums</a></li>
      
      <li><a href="/show/healthmix">Health Mix</a></li>
      
      <li><a href="/show/sweets">Sweets</a></li>
      
      <li><a href="/show/snacks">Snacks</a></li>
      
      <li><a href="/show/jaggerysweets">Jaggery Sweets</a></li>
    
    </ul>
    </div>
     <% if flash.any? %>
                  <% flash.each do |msg, type| %>
                  <div  class="alert-msg">
                    <p><%= type %></p>
                  </div>
                  <% end %>
                  <% end %>
</div>

<div class="img_con">
  <a href='/show/snacks'> <%= image_tag 'Sweet.png', alt: 'Search_Icon', class: 'main_img_1'%></a>
  <a href='/show/papads&Fryums'> <%= image_tag 'pappads.jpg', alt: 'Search_Icon', class: 'main_img_2'%></a>
  <a href='/show/sweets'> <%= image_tag 'sweets.jpg', alt: 'Search_Icon', class: 'main_img_3'%></a>
  <a href='/show/healthmix'> <%= image_tag 'healthMix.png', alt: 'Search_Icon', class: 'main_img_4'%></a>
</div>

<div class="text_div">

  <%= image_tag 'happy.png', alt: 'Happy_customer', class: ''%>
  <%= image_tag 'love.png', alt: 'Prepared_with_love', class: ''%>
  <%= image_tag 'delivered.png', alt: 'delivery', class: ''%>
  <div class="txt">
    <p class="p1">1000+ Happy Customers</p>
    <p class="p2">Prepared with love Everyday</p>
    <p class="p3">Free shipping above Rs 499/-</p>

  </div>
</div>
<% current_user = session[:current_user_id] %>
<%# <p class="ptag">user is  <%= current_user %>  </p> 
<!-- <div class="hm_podis">
  <p>HOMEMADE PODIS</p>
  <div class="podi_div">
    <a href=""><%= image_tag 'podi.jpg', alt: 'Happy_customer', class: ''%></a>
    <a href=""><%= image_tag 'masala.jpg', alt: 'Prepared_with_love', class: ''%></a>
    <a href=""><%= image_tag 'masala.jpg', alt: 'Prepared_with_love', class: ''%></a>
    <a href=""><%= image_tag 'view.jpg', alt: 'delivery', class: ''%></a>
  
  </div>
</div>
<div class="hm_podis">
  <p>HOMEMADE PICKLES</p>
  <div class="podi_div">
    <a href=""><%= image_tag 'maavadu.jpg', alt: 'Happy_customer', class: ''%></a>
    <a href=""><%= image_tag 'readymix.jpg', alt: 'Prepared_with_love', class: ''%></a>
    <a href=""><%= image_tag 'pickles.jpg', alt: 'Prepared_with_love', class: ''%></a>
    <a href=""><%= image_tag 'etc.jpg', alt: 'delivery', class: ''%></a>
  </div>
</div> -->
<div class="blog">
<p>Recipe Blogs</p>
<div>
  <p class="line">____________</p>
</div>
<div class="blog_img">
  <a href=""><%= image_tag 'muruku.jpg', alt: 'delivery', class: ''%></a>
  <a href=""><%= image_tag 'Boli.jpg', alt: 'delivery', class: ''%></a>
  <a href=""><%= image_tag 'viewMore.jpg', alt: 'delivery', class: ''%></a>
</div>

</div>

<!-- <script src="https://kit.fontawesome.com/0da631b9cc.js" crossorigin="anonymous">
  
</script> -->
<script>
  function onclickUser(){
    
  }
</script>

app/views/home/search.html.erb
<div class="nav_con">
  <div class="nav_subCon">
  <form action='/search'>
    <input type="text" name='q' placeholder="Find your snack" class="search">
    <%= image_tag 'Search.png', alt: 'Search_Icon', class: 'search_img'%>
  </form>
    <div class="heart">
      <div class="drop-down-container">
        <a class="ace"  href=''> <%= image_tag 'User.png', alt: 'Search_Icon', class: 'icons', id: 'user' %>
       
         <% if session[:current_user_id]  == nil %> 
          <div id="log" class="drop-down">
            <ul>
              <li><a href="/login">Login</a></li>
                <%# <% else %> 
                <%# <li><a href="/logout" data-method="delete">Log Out</a></li> %>
               
            </ul>
          </div>
        </a>
      </div>
      <%else%>
       <div id="log" class="drop-down">
            <ul>
              <%# <li><a href="/login">Login</a></li> %>
               
                <li><a href="/logout" data-method="delete">Log Out</a></li>
               
            </ul>
          </div>
        </a>
      </div>
        <%end %>  
      
    <a href='wish-list'> <%= image_tag 'favorite.png', alt: 'Search_Icon', class: 'icons'%></a>
    <a href='/cart'> <%= image_tag 'cart.png', alt: 'Search_Icon', class: 'icons'%></a>
  </div>
  </div>
  
  <div class="nav_div">
    <ul>
      <li><a href="/show/pickles">Pickles</a></li>
        
      <li><a href="/show/papads&Fryums">Papads & Fryums</a></li>
      
      <li><a href="/show/healthmix">Health Mix</a></li>
      
      <li><a href="/show/sweets">Sweets</a></li>
      
      <li><a href="/show/snacks">Snacks</a></li>
      
      <li><a href="/show/jaggerysweets">Jaggery Sweets</a></li>
    
    </ul>
    </div>
    <!-- <%= button_to "Logout", logout_path, method: :delete %> -->
</div>

<% unless @filtered_items.length > 0 %>
    <p class="no-result"> No results found!    </p>
<% end %>
<% @filtered_items.each do |cart_item| %>

<div class="cart-container">
 <%# <% @cart_items.each do |cart_item| %>
<div class="cart-whole-item-container">
    <div class="cart-item-container">
        <div class="cart-img-container"> 
          <a href="/item/<%= cart_item['id'] %>">
            <%= image_tag cart_item['img_url'] , alt: 'cart-item', class: 'cart-item-img'%>
          </a>
        </div>
        <div class="item-bttn">
             <!-- <a href="cart_page/<%= cart_item['id']%>">  <%= image_tag 'bin.png' , alt: 'cart-item', class: 'cart-btn-img'%></a> -->
             <a href="/wishlist/<%= cart_item['id']%>"> <%= image_tag 'eye.png' , alt: 'eye', class: 'item-btn-img'%></a>
             <a href="/cart/<%= cart_item['id']%>"> <%= image_tag 'Cart.png' , alt: 'eye', class: 'item-btn-img'%></a>
            
           </div>
    </div>
    <div class="item-content">
      <p class="item-name-ptag">
        <%= cart_item['item_name'].upcase
        %> (  <%= cart_item['quantity']
        %>G  )
      </p>
        <p class="item-price-ptag">
          Rs. <%= cart_item['price'] %>
        </p>
    </div>
  </div>
    <%# <% end %>
    
    
</div>
<%end%>

app/views/home/user_profile.html.erb
<div class="user-profile-container">
<div class="outline-inner-div"></div>
</div>

app/views/home/wishlist.html.erb
<% wl_products = $wishlist_products %>
<div class="nav_con">
  <div class="nav_subCon">
  <form action='/search'>
    <input type="text" name='q' placeholder="Find your snack" class="search">
    <%= image_tag 'Search.png', alt: 'Search_Icon', class: 'search_img'%>
  </form>
    <div class="heart">
      <div class="drop-down-container">
        <a class="ace"  href=''> <%= image_tag 'User.png', alt: 'Search_Icon', class: 'icons', id: 'user' %>
       
         <% if session[:current_user_id]  == nil %> 
          <div id="log" class="drop-down">
            <ul>
              <li><a href="/login">Login</a></li>
                <%# <% else %> 
                <%# <li><a href="/logout" data-method="delete">Log Out</a></li> %>
               
            </ul>
          </div>
        </a>
      </div>
      <%else%>
       <div id="log" class="drop-down">
            <ul>
              <%# <li><a href="/login">Login</a></li> %>
               
                <li><a href="/logout" data-method="delete">Log Out</a></li>
               
            </ul>
          </div>
        </a>
      </div>
        <%end %>  
      
    <a href='wish-list'> <%= image_tag 'favorite.png', alt: 'Search_Icon', class: 'icons'%></a>
    <a href='/cart'> <%= image_tag 'cart.png', alt: 'Search_Icon', class: 'icons'%></a>
  </div>
  </div>
  
  <div class="nav_div">
    <ul>
      <li><a href="/show/pickles">Pickles</a></li>
        
      <li><a href="/show/papads&Fryums">Papads & Fryums</a></li>
      
      <li><a href="/show/healthmix">Health Mix</a></li>
      
      <li><a href="/show/sweets">Sweets</a></li>
      
      <li><a href="/show/snacks">Snacks</a></li>
      
      <li><a href="/show/jaggerysweets">Jaggery Sweets</a></li>
    
    </ul>
    </div>
    <!-- <%= button_to "Logout", logout_path, method: :delete %> -->
</div>


<!-- <div class="wishlist-container">
  <% @items.each do|wishlist_items|%>
  <div class="wishlist-item-container">
    <div class="wishlist-img-container">
      <a href=""> <%= image_tag  wishlist_items['img_url'] , alt: 'wishlist_item'  %></a>
    </div>
    <div class="wishlist-btn-container">
      <a href=""><%= image_tag 'eye.png' , alt: 'wishlist_btn' %></a>
      <a href=""> <%= image_tag 'cart.png' , alt: 'wishlist_btn' %></a>
    </div>
  </div>
  <div class="hover-div">
    <a href="wish-list/<%= wishlist_items[:id]%>" data-method="delete"><%= image_tag 'love.png' , alt: 'wishlist-like-img', class: 'wishlist-like-img'%></a>
    

  </div>
  <% end %>
</div> -->

<% current_user = session[:current_user_id] %>

<% if session[:current_user_id] == nil %>
 <div class="wl-container">
 
 <%# <p class="wl-empty-content">Your wishlist is empty!</p> %>
 <p class="wl-connect-content">Please connect with us! </p><%= image_tag 'smiley.png', alt: 'smiley', class: 'smiley-emoji'%>
 </div>

<% else %>
       <%if Wishlist.where(user_id: current_user['id']) == []  %>
      <div class="wl-container">
      
      <p class="wl-empty-content">Your wishlist is empty!</p>
      <p class="wl-connect-content">Please add some products to your wishlist! </p><%= image_tag 'smiley.png' , alt: 'smiley', class: 'smiley-emoji'%>
      </div>
         <%else %> 
      
      <%# <p class="wl-empty-content"> <%  current_user %></p>
      <% if flash.any? %>
                  <% flash.each do |msg, type| %>
                  <div  class="alert-msg">
                    <p><%= type %></p>
                  </div>
                  <% end %>
                  <% end %>


     <div class="wl-container">
       
      <% Wishlist.where(user_id: current_user['id']).map do |item|%>
      <% wl_items = Item.joins(:wishlist).where(id:item.item_id).map do |cart_item| %>
     <div class="wishlist-whole-item-container">
         <div class="wl-item-container">
             <div class="wl-img-container"> 
               <a href="/item/<%= cart_item['id'] %>">
                 <%= image_tag cart_item['img_url'] , alt: 'cart-item', class: 'wl-item-img'%>
               </a>
             </div>
             <div class="wl-bttn">
               <a href="wish-list/<%= cart_item['id']%>" data-method="delete">    <%= image_tag 'bin.png' , alt: 'cart-item', class: 'wl-btn-img'%></a>
               <a href="/wishlist/<%= cart_item['id']%>"> <%= image_tag 'eye.png' , alt: 'eye', class: 'wl-btn-img'%></a>
               <a href="/wl/<%= cart_item['id']%>"> <%= image_tag 'Cart.png' , alt: 'eye', class: 'wl-btn-img'%></a>
             </div>
         </div>

         <div class="item-content">
           <p class="item-name-ptag">
             <%= cart_item['item_name'].upcase
             %> (  <%= cart_item['quantity'] %> G  )
           </p>
             <p class="item-price-ptag">
               Rs. <%= cart_item['price'] %>
             </p>
         </div>
         
       </div>
     
        
       <%end%> 
       <%end%>
       <%end%>  
       <%end%>
 </div>



 